kind: Job
apiVersion: batch/v1
metadata:
  name: $APP_NAME-$BUILD_NUMBER
  namespace: $PROJECT_NAMESPACE
spec:
  #backoffLimit: 5
  template:
    spec:
      initContainers:
      - name: prepare-word_vector
        # hub.data.wust.edu.cn:30880/ygtao/mnist-word_vector:v1.0
        image: $word_vector_IMAGE
        command: ['sh', '-c', 'mv /word_vector/* /tempdir;echo the init container is used to prepare word_vector for your code!']
        volumeMounts:
        - name: shared-word_vector
          mountPath: /tempdir
      containers:
        - name: $APP_NAME-$BUILD_NUMBER
          image: $REGISTRY/$HARBOR_NAMESPACE/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
          volumeMounts:
          - name: shared-word_vector
            mountPath: /word_vector
          resources:
            limits:
              nvidia.com/gpu: 1
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
       - name: $HARBOR_LOGIN_SECRET_NAME
      restartPolicy: Never
      volumes:
      - name: shared-word_vector
        emptyDir: {}